### ISSUE TITLE
Airdrop 

### ISSUE THREAD

**Issue by Ali890000** [coinscope-co/kyc#2]
Can't claim airdrop  when I try to contact to the admin on telegram group they advise me to connect my wallet to their website to claim.  they say its safe wich I refuse to do

**Comment by forestPump89** [comment]
Which airdrop are you trying to claim?

**Comment by Ali890000** [comment]
Graywolf 

0xb8ced1cadc91826697f17db66cb3837da072f89f

**Comment by forestPump89** [comment]
I am afraid thats related to their anti-bot functionality. They have to exclude the airdrop contract from being blocked

**Comment by Ali890000** [comment]
What you are saying it's okay to connect my wallet  on their website?
